### ISSUE TITLE
cannot connect to da2

### ISSUE THREAD

**Issue by jalomas7** [fdac15/news#5]
Like the title says, I can't ssh into da2.eecs.utk.edu to access the docker. I get "ssh: connect to host da2.eecs.utk.edu port 9015: No route to host" every time I try to connect now. I'm using the same information as I have been all semester without issue, but this has been ongoing for about two days now. I was just wondering if this was a known issue.

**Comment by almasaeed2010** [comment]
I have the same problem. The error message says:

```
ssh: connect to host da2.eecs.utk.edu port 9002: Connection refused
```

**Comment by tapjdey** [comment]
Same from my end too ... 
 ssh: connect to host da2.eecs.utk.edu port 9036: No route to host

I can connect to the da2 server standalone ... seems the docker container is down

**Comment by audrism** [comment]
Docker firewall got hosed. Restarted, please check if it works.
Apologies, Audris

**Comment by audrism** [comment]
Docker firewall got hosed. Restarted, please check if it works.
Apologies, Audris

**Comment by almasaeed2010** [comment]
Yup mine is fixed :+1:

**Comment by audrism** [comment]
closing: please note that I had to restart the containers and scripts, if running in the containers, have been terminated :-(
