### ISSUE TITLE
Can't connect to da2 (Public key denied) after ssh'ing into da3

### ISSUE THREAD

**Issue by jaredthecoder** [fdac15/news#7]
I can't connect to da2 over ssh after I connected to da3 through ssh. It is saying my public key is invalid.

Specifically, when I ssh to da2, it says:
`Permission denied (publickey).`

**Comment by jaredthecoder** [comment]
Fixed. It started working again. Closing.

**Comment by audrism** [comment]
Please try again.

Audris
